global:
  slack_api_url: 'https://hooks.slack.com/services/YOUR_HASH_ID'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#your_channel'
